### ISSUE TITLE
`//` in string breaks highlighting

### ISSUE THREAD

**Issue by varon** [kaashyapan/tree-sitter-fsharp#1]
Thank you for continuing this project!

Simple bug report:
```fs
let howToBreakTheHighlighting = "//"
```
Put that line anywhere in your code to instantly break all following highlighting for the rest of the file.

This is a pretty show stopping issue because any file with a URL (i.e. `https://` breaks)

**Comment by kaashyapan** [comment]
Hi

I edited the readme. 

Please continue to report bugs in the original repo. I think the maintainers are still responding. 
I intend to put some effort on improving this project and will look into fixing this bug as well.

**Comment by varon** [comment]
Understood. Given the disconnected fork + reset commit history (why was this done?), that was not an expected answer.

Also, as this fork is used in `helix-editor` - https://github.com/helix-editor/helix/pull/7619/files#diff-f3ea26d68561619ec2cb9ee551ef03916b667bd5f55b2ae2c54cae96e8821b2eR2678, it seemed to make the most sense to add that here.

**Comment by TheJayMann** [comment]
Given that this has been fixed upstream, that upstream currently does not publish parser.c as is required by helix editor, and that helix editor is currently configured to use this repository, can we have this repository pull in the new changes and update the generated files so that helix can be configured to pull in the grammar with this issue fixed, hopefully before the next release, which, based on the frequency of previous releases, is likely soon?

**Comment by kaashyapan** [comment]
Merged 
https://github.com/helix-editor/helix/pull/8024
